import { faker } from '@faker-js/faker';
import { test, expect } from '@playwright/test';

test('test valid admin login credential', async ({ page }) => {
  const firstName = faker.person.firstName();
  const middleName = faker.person.middleName();
  const lastName = faker.person.lastName();
  const birthday = faker.date.birthdate({ min: 18, max: 50, mode: 'age' }).toISOString().split('T')[0];
  const address = faker.location.streetAddress();
  const number = '09' + faker.number.int({ min: 100000000, max: 999999999 }).toString();
  const fakeEmail = `vegie+${firstName.toLowerCase()}.${lastName.toLowerCase()}@skunkworks.ai`;
  const sponsorCode = 'ASC-6928862736';
  
  await page.goto('https://smart-city-ascendra-por-ppd2-g7c0e7echsdse3cq.southeastasia-01.azurewebsites.net');
  console.log('✅ Successfully navigated to login page');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('sysadmin');
  console.log('✅ Successfully inputs username');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('@sC3ndraA!i25');
  console.log('✅ Successfully inputs password');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('User Management', { exact: true }).waitFor();
  // await page.pause(); // Pause to inspect the page after login
  console.log('✅ Admin logged in successfully');
  await page.getByRole('button', { name: 'Add Free Slot' }).click();
  await page.getByRole('textbox', { name: 'Sponsor ID *' }).fill(sponsorCode);
  console.log('✅ Successfully inputs Sponsor ID');
  await page.getByRole('combobox', { name: 'Rank *' }).click();
  await page.getByRole('option', { name: 'Builder' }).click();
  console.log('✅ Successfully selects Rank');
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill(firstName);
  console.log('✅ Successfully inputs First Name');
  await page.getByRole('textbox', { name: 'First Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Middle Name' }).fill(middleName);
  console.log('✅ Successfully inputs Middle Name');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name *' }).fill(lastName);
  await page.getByRole('textbox', { name: 'Last Name *' }).press('Tab');
  console.log('✅ Successfully inputs Last Name');
  await page.getByRole('textbox', { name: 'Birthday *' }).fill(birthday);
  await page.getByRole('combobox', { name: 'Gender *' }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByRole('combobox', { name: 'Status *' }).click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).fill(fakeEmail);
  console.log('✅ Successfully inputs ' + fakeEmail);
  await page.getByRole('textbox', { name: 'Contact Number *' }).click();
  await page.getByRole('textbox', { name: 'Contact Number *' }).fill(number);
  console.log('✅ Successfully inputs Contact Number');
  await page.getByRole('textbox', { name: 'Address *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address *', exact: true }).fill(address);
  await page.getByRole('button', { name: 'Save Free Slot' }).click();
  console.log('✅ Successfully clicks Save Free Slot');
  await page.getByRole('textbox', { name: 'Search Name' }).click();
  await page.getByRole('textbox', { name: 'Search Name' }).fill(firstName + ' ' + middleName + ' ' + lastName);
  console.log('✅ Successfully inputs ' + firstName + ' ' + middleName + ' ' + lastName + ' in Search Name');
  await expect(page.getByText(fakeEmail)).toBeVisible();
  console.log('✅ Successfully found the newly created free slot');
  console.log('✅ Free slot creation using valid data test passed successfully');

});