name: Playwright Tests

on:
  repository_dispatch:
    types: [run-playwright]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'     # ✅ Cache node_modules

      - name: Install dependencies
        run: npm ci

      # ✅ Cache Playwright browsers to avoid re-download
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # ✅ Install browsers only if missing
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      # ✅ Run only tests in tests/ folder
      - name: Run Playwright Tests in Parallel
        run: npx playwright test tests --workers=4 --reporter=line

      # 📦 Upload report
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
